'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace wsGLUtlities
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://schemas.lawson.com/GLUtilities", ConfigurationName:="wsGLUtlities.GLUtilities")>  _
    Public Interface GLUtilities
        
        'CODEGEN: Generating message contract since the operation Average_Cost_Adjust is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Average_Cost_Adjust(ByVal request As wsGLUtlities.Average_Cost_Adjust) As wsGLUtlities.Average_Cost_AdjustResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function Average_Cost_AdjustAsync(ByVal request As wsGLUtlities.Average_Cost_Adjust) As System.Threading.Tasks.Task(Of wsGLUtlities.Average_Cost_AdjustResponse)
        
        'CODEGEN: Generating message contract since the operation LoadAccountingRules is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LoadAccountingRules(ByVal request As wsGLUtlities.LoadAccountingRules) As wsGLUtlities.LoadAccountingRulesResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function LoadAccountingRulesAsync(ByVal request As wsGLUtlities.LoadAccountingRules) As System.Threading.Tasks.Task(Of wsGLUtlities.LoadAccountingRulesResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://lawson.com/ws/credentials")>  _
    Partial Public Class lws
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private userField As String
        
        Private passwordField As String
        
        Private companyField As String
        
        Private divisionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property user() As String
            Get
                Return Me.userField
            End Get
            Set
                Me.userField = value
                Me.RaisePropertyChanged("user")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer", Order:=2)>  _
        Public Property company() As String
            Get
                Return Me.companyField
            End Get
            Set
                Me.companyField = value
                Me.RaisePropertyChanged("company")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property division() As String
            Get
                Return Me.divisionField
            End Get
            Set
                Me.divisionField = value
                Me.RaisePropertyChanged("division")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="ct_1", [Namespace]:="http://schemas.lawson.com/GLUtilities/LoadAccountingRules")>  _
    Partial Public Class ct_11
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.lawson.com/GLUtilities/LoadAccountingRules")>  _
    Partial Public Class LoadAccountingRulesResponseType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private cRS395Field As ct_11
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property CRS395() As ct_11
            Get
                Return Me.cRS395Field
            End Get
            Set
                Me.cRS395Field = value
                Me.RaisePropertyChanged("CRS395")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="ct_0", [Namespace]:="http://schemas.lawson.com/GLUtilities/LoadAccountingRules")>  _
    Partial Public Class ct_01
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private accountingDimension1Field As String
        
        Private accountingDimension2Field As String
        
        Private accountingDimension3Field As String
        
        Private accountingDimension4Field As String
        
        Private accountingDimension5Field As String
        
        Private accountingDimension6Field As String
        
        Private accountingDimension7Field As String
        
        Private dynamicValueFromSelectedObject2Field As String
        
        Private dynamicValueFromSelectedObject3Field As String
        
        Private dynamicValueFromSelectedObject4Field As String
        
        Private dynamicValueFromSelectedObject5Field As String
        
        Private dynamicValueFromSelectedObject6Field As String
        
        Private dynamicValueFromSelectedObject7Field As String
        
        Private accountingEventField As String
        
        Private accountingTypeField As String
        
        Private fromDateField As String
        
        Private divisionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property AccountingDimension1() As String
            Get
                Return Me.accountingDimension1Field
            End Get
            Set
                Me.accountingDimension1Field = value
                Me.RaisePropertyChanged("AccountingDimension1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property AccountingDimension2() As String
            Get
                Return Me.accountingDimension2Field
            End Get
            Set
                Me.accountingDimension2Field = value
                Me.RaisePropertyChanged("AccountingDimension2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property AccountingDimension3() As String
            Get
                Return Me.accountingDimension3Field
            End Get
            Set
                Me.accountingDimension3Field = value
                Me.RaisePropertyChanged("AccountingDimension3")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=3)>  _
        Public Property AccountingDimension4() As String
            Get
                Return Me.accountingDimension4Field
            End Get
            Set
                Me.accountingDimension4Field = value
                Me.RaisePropertyChanged("AccountingDimension4")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
        Public Property AccountingDimension5() As String
            Get
                Return Me.accountingDimension5Field
            End Get
            Set
                Me.accountingDimension5Field = value
                Me.RaisePropertyChanged("AccountingDimension5")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=5)>  _
        Public Property AccountingDimension6() As String
            Get
                Return Me.accountingDimension6Field
            End Get
            Set
                Me.accountingDimension6Field = value
                Me.RaisePropertyChanged("AccountingDimension6")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=6)>  _
        Public Property AccountingDimension7() As String
            Get
                Return Me.accountingDimension7Field
            End Get
            Set
                Me.accountingDimension7Field = value
                Me.RaisePropertyChanged("AccountingDimension7")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=7)>  _
        Public Property DynamicValueFromSelectedObject2() As String
            Get
                Return Me.dynamicValueFromSelectedObject2Field
            End Get
            Set
                Me.dynamicValueFromSelectedObject2Field = value
                Me.RaisePropertyChanged("DynamicValueFromSelectedObject2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=8)>  _
        Public Property DynamicValueFromSelectedObject3() As String
            Get
                Return Me.dynamicValueFromSelectedObject3Field
            End Get
            Set
                Me.dynamicValueFromSelectedObject3Field = value
                Me.RaisePropertyChanged("DynamicValueFromSelectedObject3")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=9)>  _
        Public Property DynamicValueFromSelectedObject4() As String
            Get
                Return Me.dynamicValueFromSelectedObject4Field
            End Get
            Set
                Me.dynamicValueFromSelectedObject4Field = value
                Me.RaisePropertyChanged("DynamicValueFromSelectedObject4")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=10)>  _
        Public Property DynamicValueFromSelectedObject5() As String
            Get
                Return Me.dynamicValueFromSelectedObject5Field
            End Get
            Set
                Me.dynamicValueFromSelectedObject5Field = value
                Me.RaisePropertyChanged("DynamicValueFromSelectedObject5")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=11)>  _
        Public Property DynamicValueFromSelectedObject6() As String
            Get
                Return Me.dynamicValueFromSelectedObject6Field
            End Get
            Set
                Me.dynamicValueFromSelectedObject6Field = value
                Me.RaisePropertyChanged("DynamicValueFromSelectedObject6")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=12)>  _
        Public Property DynamicValueFromSelectedObject7() As String
            Get
                Return Me.dynamicValueFromSelectedObject7Field
            End Get
            Set
                Me.dynamicValueFromSelectedObject7Field = value
                Me.RaisePropertyChanged("DynamicValueFromSelectedObject7")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property AccountingEvent() As String
            Get
                Return Me.accountingEventField
            End Get
            Set
                Me.accountingEventField = value
                Me.RaisePropertyChanged("AccountingEvent")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=14)>  _
        Public Property AccountingType() As String
            Get
                Return Me.accountingTypeField
            End Get
            Set
                Me.accountingTypeField = value
                Me.RaisePropertyChanged("AccountingType")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=15)>  _
        Public Property FromDate() As String
            Get
                Return Me.fromDateField
            End Get
            Set
                Me.fromDateField = value
                Me.RaisePropertyChanged("FromDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=16)>  _
        Public Property Division() As String
            Get
                Return Me.divisionField
            End Get
            Set
                Me.divisionField = value
                Me.RaisePropertyChanged("Division")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.lawson.com/GLUtilities/LoadAccountingRules")>  _
    Partial Public Class LoadAccountingRulesType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private cRS395Field As ct_01
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property CRS395() As ct_01
            Get
                Return Me.cRS395Field
            End Get
            Set
                Me.cRS395Field = value
                Me.RaisePropertyChanged("CRS395")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.lawson.com/GLUtilities/Average_Cost_Adjust")>  _
    Partial Public Class ct_1
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.lawson.com/GLUtilities/Average_Cost_Adjust")>  _
    Partial Public Class Average_Cost_AdjustResponseType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private cAS370Field As ct_1
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property CAS370() As ct_1
            Get
                Return Me.cAS370Field
            End Get
            Set
                Me.cAS370Field = value
                Me.RaisePropertyChanged("CAS370")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.lawson.com/GLUtilities/Average_Cost_Adjust")>  _
    Partial Public Class ct_0
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private facilityField As String
        
        Private itemNumberField As String
        
        Private averageCostField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Facility() As String
            Get
                Return Me.facilityField
            End Get
            Set
                Me.facilityField = value
                Me.RaisePropertyChanged("Facility")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property ItemNumber() As String
            Get
                Return Me.itemNumberField
            End Get
            Set
                Me.itemNumberField = value
                Me.RaisePropertyChanged("ItemNumber")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property AverageCost() As String
            Get
                Return Me.averageCostField
            End Get
            Set
                Me.averageCostField = value
                Me.RaisePropertyChanged("AverageCost")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.lawson.com/GLUtilities/Average_Cost_Adjust")>  _
    Partial Public Class Average_Cost_AdjustType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private cAS370Field As ct_0
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property CAS370() As ct_0
            Get
                Return Me.cAS370Field
            End Get
            Set
                Me.cAS370Field = value
                Me.RaisePropertyChanged("CAS370")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Average_Cost_Adjust
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://lawson.com/ws/credentials")>  _
        Public lws As wsGLUtlities.lws
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Average_Cost_Adjust", [Namespace]:="http://schemas.lawson.com/GLUtilities/Average_Cost_Adjust", Order:=0)>  _
        Public Average_Cost_Adjust1 As wsGLUtlities.Average_Cost_AdjustType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal lws As wsGLUtlities.lws, ByVal Average_Cost_Adjust1 As wsGLUtlities.Average_Cost_AdjustType)
            MyBase.New
            Me.lws = lws
            Me.Average_Cost_Adjust1 = Average_Cost_Adjust1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Average_Cost_AdjustResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Average_Cost_AdjustResponse", [Namespace]:="http://schemas.lawson.com/GLUtilities/Average_Cost_Adjust", Order:=0)>  _
        Public Average_Cost_AdjustResponse1 As wsGLUtlities.Average_Cost_AdjustResponseType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Average_Cost_AdjustResponse1 As wsGLUtlities.Average_Cost_AdjustResponseType)
            MyBase.New
            Me.Average_Cost_AdjustResponse1 = Average_Cost_AdjustResponse1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoadAccountingRules
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://lawson.com/ws/credentials")>  _
        Public lws As wsGLUtlities.lws
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoadAccountingRules", [Namespace]:="http://schemas.lawson.com/GLUtilities/LoadAccountingRules", Order:=0)>  _
        Public LoadAccountingRules1 As wsGLUtlities.LoadAccountingRulesType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal lws As wsGLUtlities.lws, ByVal LoadAccountingRules1 As wsGLUtlities.LoadAccountingRulesType)
            MyBase.New
            Me.lws = lws
            Me.LoadAccountingRules1 = LoadAccountingRules1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoadAccountingRulesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoadAccountingRulesResponse", [Namespace]:="http://schemas.lawson.com/GLUtilities/LoadAccountingRules", Order:=0)>  _
        Public LoadAccountingRulesResponse1 As wsGLUtlities.LoadAccountingRulesResponseType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LoadAccountingRulesResponse1 As wsGLUtlities.LoadAccountingRulesResponseType)
            MyBase.New
            Me.LoadAccountingRulesResponse1 = LoadAccountingRulesResponse1
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface GLUtilitiesChannel
        Inherits wsGLUtlities.GLUtilities, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GLUtilitiesClient
        Inherits System.ServiceModel.ClientBase(Of wsGLUtlities.GLUtilities)
        Implements wsGLUtlities.GLUtilities
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsGLUtlities_GLUtilities_Average_Cost_Adjust(ByVal request As wsGLUtlities.Average_Cost_Adjust) As wsGLUtlities.Average_Cost_AdjustResponse Implements wsGLUtlities.GLUtilities.Average_Cost_Adjust
            Return MyBase.Channel.Average_Cost_Adjust(request)
        End Function
        
        Public Function Average_Cost_Adjust(ByVal lws As wsGLUtlities.lws, ByVal Average_Cost_Adjust1 As wsGLUtlities.Average_Cost_AdjustType) As wsGLUtlities.Average_Cost_AdjustResponseType
            Dim inValue As wsGLUtlities.Average_Cost_Adjust = New wsGLUtlities.Average_Cost_Adjust()
            inValue.lws = lws
            inValue.Average_Cost_Adjust1 = Average_Cost_Adjust1
            Dim retVal As wsGLUtlities.Average_Cost_AdjustResponse = CType(Me,wsGLUtlities.GLUtilities).Average_Cost_Adjust(inValue)
            Return retVal.Average_Cost_AdjustResponse1
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsGLUtlities_GLUtilities_Average_Cost_AdjustAsync(ByVal request As wsGLUtlities.Average_Cost_Adjust) As System.Threading.Tasks.Task(Of wsGLUtlities.Average_Cost_AdjustResponse) Implements wsGLUtlities.GLUtilities.Average_Cost_AdjustAsync
            Return MyBase.Channel.Average_Cost_AdjustAsync(request)
        End Function
        
        Public Function Average_Cost_AdjustAsync(ByVal lws As wsGLUtlities.lws, ByVal Average_Cost_Adjust1 As wsGLUtlities.Average_Cost_AdjustType) As System.Threading.Tasks.Task(Of wsGLUtlities.Average_Cost_AdjustResponse)
            Dim inValue As wsGLUtlities.Average_Cost_Adjust = New wsGLUtlities.Average_Cost_Adjust()
            inValue.lws = lws
            inValue.Average_Cost_Adjust1 = Average_Cost_Adjust1
            Return CType(Me,wsGLUtlities.GLUtilities).Average_Cost_AdjustAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsGLUtlities_GLUtilities_LoadAccountingRules(ByVal request As wsGLUtlities.LoadAccountingRules) As wsGLUtlities.LoadAccountingRulesResponse Implements wsGLUtlities.GLUtilities.LoadAccountingRules
            Return MyBase.Channel.LoadAccountingRules(request)
        End Function
        
        Public Function LoadAccountingRules(ByVal lws As wsGLUtlities.lws, ByVal LoadAccountingRules1 As wsGLUtlities.LoadAccountingRulesType) As wsGLUtlities.LoadAccountingRulesResponseType
            Dim inValue As wsGLUtlities.LoadAccountingRules = New wsGLUtlities.LoadAccountingRules()
            inValue.lws = lws
            inValue.LoadAccountingRules1 = LoadAccountingRules1
            Dim retVal As wsGLUtlities.LoadAccountingRulesResponse = CType(Me,wsGLUtlities.GLUtilities).LoadAccountingRules(inValue)
            Return retVal.LoadAccountingRulesResponse1
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsGLUtlities_GLUtilities_LoadAccountingRulesAsync(ByVal request As wsGLUtlities.LoadAccountingRules) As System.Threading.Tasks.Task(Of wsGLUtlities.LoadAccountingRulesResponse) Implements wsGLUtlities.GLUtilities.LoadAccountingRulesAsync
            Return MyBase.Channel.LoadAccountingRulesAsync(request)
        End Function
        
        Public Function LoadAccountingRulesAsync(ByVal lws As wsGLUtlities.lws, ByVal LoadAccountingRules1 As wsGLUtlities.LoadAccountingRulesType) As System.Threading.Tasks.Task(Of wsGLUtlities.LoadAccountingRulesResponse)
            Dim inValue As wsGLUtlities.LoadAccountingRules = New wsGLUtlities.LoadAccountingRules()
            inValue.lws = lws
            inValue.LoadAccountingRules1 = LoadAccountingRules1
            Return CType(Me,wsGLUtlities.GLUtilities).LoadAccountingRulesAsync(inValue)
        End Function
    End Class
End Namespace
