'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://schemas.lawson.com/UserOperations", ConfigurationName:="ServiceReference1.UserOperations")>  _
    Public Interface UserOperations
        
        'CODEGEN: Generating message contract since the operation Copy is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Copy(ByVal request As ServiceReference1.Copy) As ServiceReference1.CopyResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function CopyAsync(ByVal request As ServiceReference1.Copy) As System.Threading.Tasks.Task(Of ServiceReference1.CopyResponse)
        
        'CODEGEN: Generating message contract since the operation Delete is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Delete(ByVal request As ServiceReference1.Delete) As ServiceReference1.DeleteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function DeleteAsync(ByVal request As ServiceReference1.Delete) As System.Threading.Tasks.Task(Of ServiceReference1.DeleteResponse)
        
        'CODEGEN: Generating message contract since the operation Change is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Change(ByVal request As ServiceReference1.Change) As ServiceReference1.ChangeResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function ChangeAsync(ByVal request As ServiceReference1.Change) As System.Threading.Tasks.Task(Of ServiceReference1.ChangeResponse)
        
        'CODEGEN: Generating message contract since the operation Create is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Create(ByVal request As ServiceReference1.Create) As ServiceReference1.CreateResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function CreateAsync(ByVal request As ServiceReference1.Create) As System.Threading.Tasks.Task(Of ServiceReference1.CreateResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://lawson.com/ws/credentials")>  _
    Partial Public Class lws
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private userField As String
        
        Private passwordField As String
        
        Private companyField As String
        
        Private divisionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property user() As String
            Get
                Return Me.userField
            End Get
            Set
                Me.userField = value
                Me.RaisePropertyChanged("user")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer", Order:=2)>  _
        Public Property company() As String
            Get
                Return Me.companyField
            End Get
            Set
                Me.companyField = value
                Me.RaisePropertyChanged("company")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property division() As String
            Get
                Return Me.divisionField
            End Get
            Set
                Me.divisionField = value
                Me.RaisePropertyChanged("division")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="ct_1", [Namespace]:="http://schemas.lawson.com/UserOperations/Create")>  _
    Partial Public Class ct_13
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.lawson.com/UserOperations/Create")>  _
    Partial Public Class CreateResponseType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private mNS150Field As ct_13
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property MNS150() As ct_13
            Get
                Return Me.mNS150Field
            End Get
            Set
                Me.mNS150Field = value
                Me.RaisePropertyChanged("MNS150")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="ct_0", [Namespace]:="http://schemas.lawson.com/UserOperations/Create")>  _
    Partial Public Class ct_03
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private userField As String
        
        Private descriptionField As String
        
        Private warehouseField As String
        
        Private telephoneNumber1Field As String
        
        Private menuVersionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property User() As String
            Get
                Return Me.userField
            End Get
            Set
                Me.userField = value
                Me.RaisePropertyChanged("User")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
                Me.RaisePropertyChanged("Description")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property Warehouse() As String
            Get
                Return Me.warehouseField
            End Get
            Set
                Me.warehouseField = value
                Me.RaisePropertyChanged("Warehouse")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=3)>  _
        Public Property TelephoneNumber1() As String
            Get
                Return Me.telephoneNumber1Field
            End Get
            Set
                Me.telephoneNumber1Field = value
                Me.RaisePropertyChanged("TelephoneNumber1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
        Public Property MenuVersion() As String
            Get
                Return Me.menuVersionField
            End Get
            Set
                Me.menuVersionField = value
                Me.RaisePropertyChanged("MenuVersion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.lawson.com/UserOperations/Create")>  _
    Partial Public Class CreateType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private mNS150Field As ct_03
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property MNS150() As ct_03
            Get
                Return Me.mNS150Field
            End Get
            Set
                Me.mNS150Field = value
                Me.RaisePropertyChanged("MNS150")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="ct_1", [Namespace]:="http://schemas.lawson.com/UserOperations/Change")>  _
    Partial Public Class ct_12
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.lawson.com/UserOperations/Change")>  _
    Partial Public Class ChangeResponseType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private mNS150Field As ct_12
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property MNS150() As ct_12
            Get
                Return Me.mNS150Field
            End Get
            Set
                Me.mNS150Field = value
                Me.RaisePropertyChanged("MNS150")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="ct_0", [Namespace]:="http://schemas.lawson.com/UserOperations/Change")>  _
    Partial Public Class ct_02
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private userField As String
        
        Private descriptionField As String
        
        Private warehouseField As String
        
        Private telephoneNumber1Field As String
        
        Private menuVersionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property User() As String
            Get
                Return Me.userField
            End Get
            Set
                Me.userField = value
                Me.RaisePropertyChanged("User")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
                Me.RaisePropertyChanged("Description")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property Warehouse() As String
            Get
                Return Me.warehouseField
            End Get
            Set
                Me.warehouseField = value
                Me.RaisePropertyChanged("Warehouse")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=3)>  _
        Public Property TelephoneNumber1() As String
            Get
                Return Me.telephoneNumber1Field
            End Get
            Set
                Me.telephoneNumber1Field = value
                Me.RaisePropertyChanged("TelephoneNumber1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
        Public Property MenuVersion() As String
            Get
                Return Me.menuVersionField
            End Get
            Set
                Me.menuVersionField = value
                Me.RaisePropertyChanged("MenuVersion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.lawson.com/UserOperations/Change")>  _
    Partial Public Class ChangeType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private mNS150Field As ct_02
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property MNS150() As ct_02
            Get
                Return Me.mNS150Field
            End Get
            Set
                Me.mNS150Field = value
                Me.RaisePropertyChanged("MNS150")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="ct_1", [Namespace]:="http://schemas.lawson.com/UserOperations/Delete")>  _
    Partial Public Class ct_11
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.lawson.com/UserOperations/Delete")>  _
    Partial Public Class DeleteResponseType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private mNS150Field As ct_11
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property MNS150() As ct_11
            Get
                Return Me.mNS150Field
            End Get
            Set
                Me.mNS150Field = value
                Me.RaisePropertyChanged("MNS150")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="ct_0", [Namespace]:="http://schemas.lawson.com/UserOperations/Delete")>  _
    Partial Public Class ct_01
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private userField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property User() As String
            Get
                Return Me.userField
            End Get
            Set
                Me.userField = value
                Me.RaisePropertyChanged("User")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.lawson.com/UserOperations/Delete")>  _
    Partial Public Class DeleteType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private mNS150Field As ct_01
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property MNS150() As ct_01
            Get
                Return Me.mNS150Field
            End Get
            Set
                Me.mNS150Field = value
                Me.RaisePropertyChanged("MNS150")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.lawson.com/UserOperations/Copy")>  _
    Partial Public Class ct_1
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.lawson.com/UserOperations/Copy")>  _
    Partial Public Class CopyResponseType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private mNS150Field As ct_1
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property MNS150() As ct_1
            Get
                Return Me.mNS150Field
            End Get
            Set
                Me.mNS150Field = value
                Me.RaisePropertyChanged("MNS150")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.lawson.com/UserOperations/Copy")>  _
    Partial Public Class ct_0
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private fromUserField As String
        
        Private descriptionField As String
        
        Private warehouseField As String
        
        Private telephoneNumber1Field As String
        
        Private menuVersionField As String
        
        Private toUserField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property FromUser() As String
            Get
                Return Me.fromUserField
            End Get
            Set
                Me.fromUserField = value
                Me.RaisePropertyChanged("FromUser")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
                Me.RaisePropertyChanged("Description")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property Warehouse() As String
            Get
                Return Me.warehouseField
            End Get
            Set
                Me.warehouseField = value
                Me.RaisePropertyChanged("Warehouse")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=3)>  _
        Public Property TelephoneNumber1() As String
            Get
                Return Me.telephoneNumber1Field
            End Get
            Set
                Me.telephoneNumber1Field = value
                Me.RaisePropertyChanged("TelephoneNumber1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
        Public Property MenuVersion() As String
            Get
                Return Me.menuVersionField
            End Get
            Set
                Me.menuVersionField = value
                Me.RaisePropertyChanged("MenuVersion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property ToUser() As String
            Get
                Return Me.toUserField
            End Get
            Set
                Me.toUserField = value
                Me.RaisePropertyChanged("ToUser")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.lawson.com/UserOperations/Copy")>  _
    Partial Public Class CopyType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private mNS150Field As ct_0
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property MNS150() As ct_0
            Get
                Return Me.mNS150Field
            End Get
            Set
                Me.mNS150Field = value
                Me.RaisePropertyChanged("MNS150")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Copy
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://lawson.com/ws/credentials")>  _
        Public lws As ServiceReference1.lws
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Copy", [Namespace]:="http://schemas.lawson.com/UserOperations/Copy", Order:=0)>  _
        Public Copy1 As ServiceReference1.CopyType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal lws As ServiceReference1.lws, ByVal Copy1 As ServiceReference1.CopyType)
            MyBase.New
            Me.lws = lws
            Me.Copy1 = Copy1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CopyResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CopyResponse", [Namespace]:="http://schemas.lawson.com/UserOperations/Copy", Order:=0)>  _
        Public CopyResponse1 As ServiceReference1.CopyResponseType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CopyResponse1 As ServiceReference1.CopyResponseType)
            MyBase.New
            Me.CopyResponse1 = CopyResponse1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Delete
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://lawson.com/ws/credentials")>  _
        Public lws As ServiceReference1.lws
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Delete", [Namespace]:="http://schemas.lawson.com/UserOperations/Delete", Order:=0)>  _
        Public Delete1 As ServiceReference1.DeleteType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal lws As ServiceReference1.lws, ByVal Delete1 As ServiceReference1.DeleteType)
            MyBase.New
            Me.lws = lws
            Me.Delete1 = Delete1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DeleteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DeleteResponse", [Namespace]:="http://schemas.lawson.com/UserOperations/Delete", Order:=0)>  _
        Public DeleteResponse1 As ServiceReference1.DeleteResponseType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DeleteResponse1 As ServiceReference1.DeleteResponseType)
            MyBase.New
            Me.DeleteResponse1 = DeleteResponse1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Change
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://lawson.com/ws/credentials")>  _
        Public lws As ServiceReference1.lws
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Change", [Namespace]:="http://schemas.lawson.com/UserOperations/Change", Order:=0)>  _
        Public Change1 As ServiceReference1.ChangeType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal lws As ServiceReference1.lws, ByVal Change1 As ServiceReference1.ChangeType)
            MyBase.New
            Me.lws = lws
            Me.Change1 = Change1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ChangeResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ChangeResponse", [Namespace]:="http://schemas.lawson.com/UserOperations/Change", Order:=0)>  _
        Public ChangeResponse1 As ServiceReference1.ChangeResponseType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ChangeResponse1 As ServiceReference1.ChangeResponseType)
            MyBase.New
            Me.ChangeResponse1 = ChangeResponse1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Create
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://lawson.com/ws/credentials")>  _
        Public lws As ServiceReference1.lws
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Create", [Namespace]:="http://schemas.lawson.com/UserOperations/Create", Order:=0)>  _
        Public Create1 As ServiceReference1.CreateType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal lws As ServiceReference1.lws, ByVal Create1 As ServiceReference1.CreateType)
            MyBase.New
            Me.lws = lws
            Me.Create1 = Create1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CreateResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CreateResponse", [Namespace]:="http://schemas.lawson.com/UserOperations/Create", Order:=0)>  _
        Public CreateResponse1 As ServiceReference1.CreateResponseType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CreateResponse1 As ServiceReference1.CreateResponseType)
            MyBase.New
            Me.CreateResponse1 = CreateResponse1
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface UserOperationsChannel
        Inherits ServiceReference1.UserOperations, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class UserOperationsClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.UserOperations)
        Implements ServiceReference1.UserOperations
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_UserOperations_Copy(ByVal request As ServiceReference1.Copy) As ServiceReference1.CopyResponse Implements ServiceReference1.UserOperations.Copy
            Return MyBase.Channel.Copy(request)
        End Function
        
        Public Function Copy(ByVal lws As ServiceReference1.lws, ByVal Copy1 As ServiceReference1.CopyType) As ServiceReference1.CopyResponseType
            Dim inValue As ServiceReference1.Copy = New ServiceReference1.Copy()
            inValue.lws = lws
            inValue.Copy1 = Copy1
            Dim retVal As ServiceReference1.CopyResponse = CType(Me,ServiceReference1.UserOperations).Copy(inValue)
            Return retVal.CopyResponse1
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_UserOperations_CopyAsync(ByVal request As ServiceReference1.Copy) As System.Threading.Tasks.Task(Of ServiceReference1.CopyResponse) Implements ServiceReference1.UserOperations.CopyAsync
            Return MyBase.Channel.CopyAsync(request)
        End Function
        
        Public Function CopyAsync(ByVal lws As ServiceReference1.lws, ByVal Copy1 As ServiceReference1.CopyType) As System.Threading.Tasks.Task(Of ServiceReference1.CopyResponse)
            Dim inValue As ServiceReference1.Copy = New ServiceReference1.Copy()
            inValue.lws = lws
            inValue.Copy1 = Copy1
            Return CType(Me,ServiceReference1.UserOperations).CopyAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_UserOperations_Delete(ByVal request As ServiceReference1.Delete) As ServiceReference1.DeleteResponse Implements ServiceReference1.UserOperations.Delete
            Return MyBase.Channel.Delete(request)
        End Function
        
        Public Function Delete(ByVal lws As ServiceReference1.lws, ByVal Delete1 As ServiceReference1.DeleteType) As ServiceReference1.DeleteResponseType
            Dim inValue As ServiceReference1.Delete = New ServiceReference1.Delete()
            inValue.lws = lws
            inValue.Delete1 = Delete1
            Dim retVal As ServiceReference1.DeleteResponse = CType(Me,ServiceReference1.UserOperations).Delete(inValue)
            Return retVal.DeleteResponse1
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_UserOperations_DeleteAsync(ByVal request As ServiceReference1.Delete) As System.Threading.Tasks.Task(Of ServiceReference1.DeleteResponse) Implements ServiceReference1.UserOperations.DeleteAsync
            Return MyBase.Channel.DeleteAsync(request)
        End Function
        
        Public Function DeleteAsync(ByVal lws As ServiceReference1.lws, ByVal Delete1 As ServiceReference1.DeleteType) As System.Threading.Tasks.Task(Of ServiceReference1.DeleteResponse)
            Dim inValue As ServiceReference1.Delete = New ServiceReference1.Delete()
            inValue.lws = lws
            inValue.Delete1 = Delete1
            Return CType(Me,ServiceReference1.UserOperations).DeleteAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_UserOperations_Change(ByVal request As ServiceReference1.Change) As ServiceReference1.ChangeResponse Implements ServiceReference1.UserOperations.Change
            Return MyBase.Channel.Change(request)
        End Function
        
        Public Function Change(ByVal lws As ServiceReference1.lws, ByVal Change1 As ServiceReference1.ChangeType) As ServiceReference1.ChangeResponseType
            Dim inValue As ServiceReference1.Change = New ServiceReference1.Change()
            inValue.lws = lws
            inValue.Change1 = Change1
            Dim retVal As ServiceReference1.ChangeResponse = CType(Me,ServiceReference1.UserOperations).Change(inValue)
            Return retVal.ChangeResponse1
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_UserOperations_ChangeAsync(ByVal request As ServiceReference1.Change) As System.Threading.Tasks.Task(Of ServiceReference1.ChangeResponse) Implements ServiceReference1.UserOperations.ChangeAsync
            Return MyBase.Channel.ChangeAsync(request)
        End Function
        
        Public Function ChangeAsync(ByVal lws As ServiceReference1.lws, ByVal Change1 As ServiceReference1.ChangeType) As System.Threading.Tasks.Task(Of ServiceReference1.ChangeResponse)
            Dim inValue As ServiceReference1.Change = New ServiceReference1.Change()
            inValue.lws = lws
            inValue.Change1 = Change1
            Return CType(Me,ServiceReference1.UserOperations).ChangeAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_UserOperations_Create(ByVal request As ServiceReference1.Create) As ServiceReference1.CreateResponse Implements ServiceReference1.UserOperations.Create
            Return MyBase.Channel.Create(request)
        End Function
        
        Public Function Create(ByVal lws As ServiceReference1.lws, ByVal Create1 As ServiceReference1.CreateType) As ServiceReference1.CreateResponseType
            Dim inValue As ServiceReference1.Create = New ServiceReference1.Create()
            inValue.lws = lws
            inValue.Create1 = Create1
            Dim retVal As ServiceReference1.CreateResponse = CType(Me,ServiceReference1.UserOperations).Create(inValue)
            Return retVal.CreateResponse1
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_UserOperations_CreateAsync(ByVal request As ServiceReference1.Create) As System.Threading.Tasks.Task(Of ServiceReference1.CreateResponse) Implements ServiceReference1.UserOperations.CreateAsync
            Return MyBase.Channel.CreateAsync(request)
        End Function
        
        Public Function CreateAsync(ByVal lws As ServiceReference1.lws, ByVal Create1 As ServiceReference1.CreateType) As System.Threading.Tasks.Task(Of ServiceReference1.CreateResponse)
            Dim inValue As ServiceReference1.Create = New ServiceReference1.Create()
            inValue.lws = lws
            inValue.Create1 = Create1
            Return CType(Me,ServiceReference1.UserOperations).CreateAsync(inValue)
        End Function
    End Class
End Namespace
